# Generated by Django 6.1 on 2026-08-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TractorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('parts_catalogue', 'Parts catalogue'), ('modification_catalogue', 'Modification catalogue'), ('workshop_manual', 'Workshop manual')], max_length=30)),
                ('language', models.CharField(default='sk', max_length=10)),
                ('original_file', models.FileField(upload_to='catalogues/originals/')),
                ('page_count', models.IntegerField(default=0)),
                ('has_text_layer', models.BooleanField(default=False)),
                ('image_dpi', models.IntegerField(blank=True, null=True)),
                ('rotation', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='catalogue.catalogue')),
                ('models_covered', models.ManyToManyField(blank=True, related_name='catalogues', to='catalogue.tractormodel')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('part_number_normalised', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name_sk', models.CharField(blank=True, max_length=300)),
                ('name_en', models.CharField(blank=True, max_length=300)),
                ('page', models.IntegerField(default=0)),
                ('figure_ref', models.CharField(blank=True, max_length=20)),
                ('position_no', models.CharField(blank=True, max_length=10)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalogue.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='JobPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='catalogue.job')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.part')),
            ],
            options={
                'ordering': ['-pinned_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_page', models.IntegerField()),
                ('end_page', models.IntegerField()),
                ('section_file', models.FileField(blank=True, upload_to='catalogues/sections/')),
                ('order', models.IntegerField(default=0)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalogue.catalogue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalogue.section'),
        ),
        migrations.AddField(
            model_name='job',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.tractormodel'),
        ),
    ]
