# Generated by Django 6.1 on 2026-08-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE VIRTUAL TABLE IF NOT EXISTS catalogue_searchindex "
            "USING fts5(section_id UNINDEXED, extracted_text);",
            reverse_sql="DROP TABLE IF EXISTS catalogue_searchindex;",
        ),
    ]
